
interestPoints: interestPoints.cpp
	g++ interestPoints.cpp -o $@ -I /usr/local/include /usr/local/lib/libopencv_*

tracking: tracking.cpp
	g++ tracking.cpp -o $@ -I /usr/local/include /usr/local/lib/libopencv_*

myTracking: myTracking.cpp
	g++ myTracking.cpp -o $@ -I /usr/local/include /usr/local/lib/libopencv_*

